### ISSUE TITLE
File is not loaded in the xlsx file

### ISSUE THREAD

**Issue by mandalsumit17** [info3g/linkedin-scrapper#2]
Hi ,

Thanks for the solution.
I have sent the range as (1, 2) and when i run the script its shows that data is scrapped, and then it shows the below mentioned error:-

Going to scrape Page 1 data
!!!!!! Data scrapped !!!!!!

Traceback (most recent call last):
  File "C:\Python27\Automation Testing\venv\lib\site-packages\xlsxwriter\workbook.py", line 311, in close
    self._store_workbook()
  File "C:\Python27\Automation Testing\venv\lib\site-packages\xlsxwriter\workbook.py", line 627, in _store_workbook
    raise e
  File "C:\Python27\Automation Testing\venv\lib\site-packages\xlsxwriter\workbook.py", line 625, in _store_workbook
    allowZip64=self.allow_zip64)
  File "C:\Python27\Lib\zipfile.py", line 1207, in __init__
    self.fp = io.open(file, filemode)
OSError: [Errno 22] Invalid argument: 'C:\\users\\s.m\\Desktop\test.xlsx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Python27/Automation Testing/Scrapping.py", line 188, in <module>
    obJH.start()
  File "C:/Python27/Automation Testing/Scrapping.py", line 183, in start
    self.writeData()
  File "C:/Python27/Automation Testing/Scrapping.py", line 179, in writeData
    workbook.close()
  File "C:\Python27\Automation Testing\venv\lib\site-packages\xlsxwriter\workbook.py", line 313, in close
    raise FileCreateError(e)
xlsxwriter.exceptions.FileCreateError: [Errno 22] Invalid argument: 'C:\\users\\s.m\\Desktop\test.xlsx'

Process finished with exit code 1

**Comment by Msumit17** [comment]
If there are 2 pages, it keeps on executing pages and gives output like
The result had only 2 pages but its was keep on executing:-

Going to scrape Page 1 data
!!!!!! Data scrapped !!!!!!
Going to scrape Page 2 data
!!!!!! Data scrapped !!!!!!
Going to scrape Page 3 data
!!!!!! Data scrapped !!!!!!
Going to scrape Page 4 data
!!!!!! Data scrapped !!!!!!
Going to scrape Page 5 data
!!!!!! Data scrapped !!!!!!
Going to scrape Page 6 data
!!!!!! Data scrapped !!!!!!

And to stop this when i closed the chrome i found this error:

Traceback (most recent call last):
  File "C:/Python27/Automation Testing/Scrapping.py", line 188, in <module>
    obJH.start()
  File "C:/Python27/Automation Testing/Scrapping.py", line 182, in start
    self.getData()
  File "C:/Python27/Automation Testing/Scrapping.py", line 37, in getData
    search = BeautifulSoup(driver.page_source, 'lxml')
  File "C:\Python27\Automation Testing\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "C:\Python27\Automation Testing\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\Automation Testing\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=77.0.3865.90)


Process finished with exit code 1
